name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci_test
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Opus dependencies
        run: sudo apt-get update && sudo apt-get install -y libopus-dev libopusfile-dev libsoxr-dev

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.24.1"

      - name: Set up tparse
        run: go install github.com/mfridman/tparse@v0.17.0

      - name: Static Check
        uses: dominikh/staticcheck-action@v1
        with:
          checks: '["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-SA1019"]'
          version: "latest"
          install-go: false

      - name: Test
        run: |
          set -euo pipefail
          go test -coverpkg=./... -race -json -v -coverprofile=coverage.out -covermode=atomic ./pkg/... 2>&1 | tee /tmp/gotest.log | tparse

      - name: Pull LiveKit Docker image
        run: |
          docker pull redis
          docker pull livekit/livekit-server:master

      - name: Test E2E
        run: |
          set -euo pipefail
          go test -coverpkg=./... -json -v -coverprofile=coverage2.out -covermode=atomic ./test/integration/... 2>&1 | tee -a /tmp/gotest.log | tparse

      - name: Upload test log
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out,./coverage2.out

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Build docker image
        run: docker build -t sip -f ./build/sip/Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::396913707045:role/OIDCKarta
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push to ECR
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./build/sip/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.ecr-login.outputs.registry }}/sip-server-prod:custom
